# Generated by Django 5.1.3 on 2025-07-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
